version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: darkbeersociety/fishbook-web
    volumes:
      - .:/fishbook
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: darkbeersociety/fishbook-frontend
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=development
